INSERT INTO CANDIDATE VALUES (1,'Gustavo');
INSERT INTO CANDIDATE VALUES (2,'Joel');
INSERT INTO CANDIDATE VALUES (3,'José');

INSERT INTO INTERVIEWER VALUES (1,'João');
INSERT INTO INTERVIEWER VALUES (2,'Francisco');
INSERT INTO INTERVIEWER VALUES (3,'Sofia');

INSERT INTO AVAILABLE_INTERVIEW_DATES VALUES (1,PARSEDATETIME('2020 09 30', 'YYYY MM DD'),1);
INSERT INTO AVAILABLE_INTERVIEW_DATES VALUES (2,PARSEDATETIME('2020 10 21', 'YYYY MM DD'),2);
INSERT INTO AVAILABLE_INTERVIEW_DATES VALUES (3,PARSEDATETIME('2020 11 20', 'YYYY MM DD'),2);
INSERT INTO AVAILABLE_INTERVIEW_DATES VALUES (4,PARSEDATETIME('2020 09 20', 'YYYY MM DD'),3);

INSERT INTO REQUESTED_INTERVIEW_DATES  VALUES (1,PARSEDATETIME('2020 09 30', 'YYYY MM DD'),1);
INSERT INTO REQUESTED_INTERVIEW_DATES  VALUES (2,PARSEDATETIME('2020 10 21', 'YYYY MM DD'),2);
INSERT INTO REQUESTED_INTERVIEW_DATES  VALUES (3,PARSEDATETIME('2020 09 19', 'YYYY MM DD'),2);
INSERT INTO REQUESTED_INTERVIEW_DATES  VALUES (4,PARSEDATETIME('2020 09 18', 'YYYY MM DD'),3);


INSERT INTO SLOT values (1, PARSEDATETIME('2020 09 30', 'YYYY MM DD'), 1 , 1);
INSERT INTO SLOT values (2, PARSEDATETIME('2020 10 21', 'YYYY MM DD'), 2 , 2);